import React from 'react';
import clsx from 'clsx';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import ProgressWorkspace from '@site/src/components/ProgressWorkspace';
import DownloadIdrButton from '@site/src/components/DownloadIdrButton';
import styles from './index.module.css';

const cards = [
  {number:'01',title:'Review the IDR',copy:'Validate the role, weekly availability, current credentials and the five highest-value property processes.',link:'/idr/intro',action:'Open executive summary'},
  {number:'02',title:'Start the 12-week sprint',copy:'Follow a sequenced plan across process mapping, data, cloud, automation, analytics, governance and leadership.',link:'/idr/12-week-plan',action:'Open sprint plan'},
  {number:'03',title:'Track 25 credential targets',copy:'Use badges, Microsoft Learn achievements, Applied Skills and exam readiness as evidence—not as disconnected trophies.',link:'/idr/credentials',action:'Open credential register'},
  {number:'04',title:'Complete applied projects',copy:'Build a governed data baseline, executive dashboard, workflow automation and PropTech operating-model evidence.',link:'/idr/projects',action:'Open project portfolio'},
  {number:'05',title:'Sync the timetable',copy:'Download the 12-week calendar or subscribe using Google Calendar, Outlook or another iCalendar-compatible client.',link:'/idr/calendar',action:'Open calendar options'},
  {number:'06',title:'Prepare mentor reviews',copy:'Raydo Matthee will facilitate fortnightly reviews and formal 30, 60 and 90-day decision gates.',link:'/idr/mentor',action:'Open mentor workflow'},
];

function Hero(){return <header className={styles.hero}><div className={styles.heroGrid}><div><div className={styles.brandLine}><img src="/img/favicon-black.svg" width="34" height="34" alt="Skunkworks Academy"/><span>Skunkworks Academy · Individual Development Roadmap</span></div><p className={styles.eyebrow}>12-month development and execution workspace</p><h1>Welcome,<span> Alberto.</span></h1><p className={styles.subtitle}>Digital Operations · Process Optimisation · PropTech Transformation</p><p className={styles.lead}>Build the capability to diagnose operational friction, establish trustworthy data, configure controlled automation, measure business value and lead a property-operations transformation pilot.</p><div className={styles.actions}><Link className={clsx('button button--primary button--lg',styles.primaryButton)} to="/idr/12-week-plan">Start the 12-week plan</Link><DownloadIdrButton className={clsx('button button--secondary button--lg',styles.secondaryButton)} label="Download PDF IDR"/><Link className={clsx('button button--secondary button--lg',styles.secondaryButton)} to="/idr/calendar">Sync study calendar</Link></div><p className={styles.privacyNote}><strong>Confidential source:</strong> use sanitised or synthetic evidence only. Do not place tenant, payment, identity or legal-document data in this public repository.</p></div><aside className={styles.heroPanel} aria-label="Roadmap summary"><div className={styles.heroMetric}><span>Placement</span><strong>Digital Transformation Practitioner</strong></div><div className={styles.heroMetric}><span>Mentor / facilitator</span><strong>Raydo Matthee</strong></div><div className={styles.heroMetric}><span>Weekly commitment</span><strong>6–8 sustainable hours</strong></div><div className={styles.heroMetric}><span>Credential sprint</span><strong>25 targets · 12 weeks</strong></div><div className={styles.heroMetric}><span>Formal reviews</span><strong>30 · 60 · 90 days</strong></div><div className={styles.heroMetric}><span>North Star</span><strong>July 2027</strong></div></aside></div></header>}

export default function Home(){return <Layout title="Welcome Alberto — Individual Development Roadmap" description="Alberto Adao’s digital operations, process optimisation and PropTech transformation roadmap."><Hero/><main className={styles.main}><div className="confidential-banner"><strong>Confidential personal-development source.</strong> This review site intentionally exposes only the learning plan and sanitised execution framework. Keep operational and personal evidence in approved private systems.</div><section className={styles.section} aria-labelledby="start-title"><div className={styles.sectionHeading}><div><p className={styles.sectionKicker}>Immediate action</p><h2 id="start-title">Start here</h2></div><span className={styles.sectionHint}>Complete through evidence and mentor review</span></div><div className={styles.cardGrid}>{cards.map(card=><Link className={styles.card} to={card.link} key={card.number}><span>{card.number}</span><h3>{card.title}</h3><p>{card.copy}</p><strong>{card.action} →</strong></Link>)}</div></section><section className={styles.northStar} aria-labelledby="north-star-title"><p className={styles.sectionKicker}>One-year North Star</p><h2 id="north-star-title" style={{position:'absolute',width:1,height:1,overflow:'hidden'}}>One-year outcome</h2><blockquote>By July 2027, Alberto should be able to lead a controlled property-operations transformation pilot, demonstrate an integrated data and workflow prototype, communicate measurable business value and supervise implementation partners with credible cloud, automation, analytics and governance knowledge.</blockquote></section><section className={styles.section} aria-labelledby="scope-title"><div className={styles.sectionHeading}><div><p className={styles.sectionKicker}>Programme scope</p><h2 id="scope-title">What success requires</h2></div></div><div className={styles.stats}><div className={styles.stat}><strong>25</strong><span>badge and credential targets</span></div><div className={styles.stat}><strong>12</strong><span>weekly learning modules</span></div><div className={styles.stat}><strong>5</strong><span>applied transformation projects</span></div><div className={styles.stat}><strong>6</strong><span>development KPIs</span></div></div></section><section className={styles.section} id="progress-workspace" aria-label="Interactive IDR progress workspace"><ProgressWorkspace/></section><section className={styles.callout} aria-labelledby="next-title"><div><p className={styles.sectionKicker}>First mentor gate</p><h2 id="next-title">Validate the roadmap before expanding the work.</h2><p>Confirm Alberto’s role, existing credentials, weekly availability and five priority property processes with Raydo Matthee.</p></div><Link className="button button--primary button--lg" to="/idr/mentor">Prepare the first review</Link></section></main></Layout>}
