import React from'react';
const lines=[
'INDIVIDUAL DEVELOPMENT ROADMAP','Alberto Antonio Carvalho Cabral Adao','Digital Operations, Process Optimisation and PropTech Transformation','Prepared by Skunkworks Academy - Training and Career Development','Report date: 16 July 2026','Review period: 12 months with 30, 60 and 90-day checkpoints','Mentor and facilitator: Raydo Matthee','',
'PROVISIONAL PLACEMENT','Digital Transformation Practitioner - Business Operations and Process Optimisation.','Primary pathway: integrated property operations, data-driven decision-making and low-code automation.','Secondary pathway: digital product leadership and PropTech entrepreneurship.','',
'ONE-YEAR NORTH STAR','By July 2027, Alberto should be able to lead a controlled property-operations transformation pilot,','demonstrate an integrated data and workflow prototype, communicate measurable business value, and supervise','implementation partners with credible cloud, automation, analytics and governance knowledge.','',
'PRIORITY DEVELOPMENT GAPS','1. Integrated data model and authoritative data sources.','2. Process discipline, controls, hand-offs and exception paths.','3. Cloud, Microsoft 365 and Power Platform literacy.','4. Low-code automation with approvals, audit, testing and rollback.','5. Analytics for occupancy, collections, arrears, vacancies, maintenance and profitability.','6. POPIA, access control, consent, retention, backup and vendor governance.','7. Sanitised portfolio evidence and disciplined leadership cadence.','',
'12-WEEK EXECUTION PLAN','Week 1: IDR validation, Enterprise Design Thinking and Data Literacy.','Week 2: Agile, project management, process mapping and system inventory.','Week 3: Cloud concepts, Azure architecture, data-source inventory and ownership.','Week 4: Azure governance, AZ-900 readiness, data dictionary and KPI ownership.','Week 5: Power Platform fundamentals and a controlled approval-flow design.','Week 6: Power Apps, Power BI, process mapping, app and dashboard design.','Week 7: Data Fundamentals, Power Query, reconciliation and canvas-app evidence.','Week 8: Process mining, synthetic event logs, bottlenecks and improvement backlog.','Week 9: Executive dashboard, reporting runbook and Cloud Computing Fundamentals.','Week 10: Cybersecurity, POPIA, access model, privacy classification and risk register.','Week 11: Governed AI, Power Automate Applied Skill, testing, oversight and rollback.','Week 12: PL-900 readiness, capstone presentation and 90-day go/no-go decision.','',
'25 BADGE AND CREDENTIAL TARGETS','1. Enterprise Design Thinking Practitioner','2. Data Literacy','3. Agile Explorer','4. Project Management Fundamentals','5. Getting Started with Data','6. Describe cloud concepts','7. Describe Azure architecture and services','8. Describe Azure management and governance','9. Microsoft Certified: Azure Fundamentals (AZ-900) - stretch','10. Power Platform business value','11. Power Apps capabilities','12. Power Automate capabilities','13. Power BI capabilities','14. Business process mapping','15. Create and manage canvas apps with Power Apps','16. Data Fundamentals','17. Introduction to Power Automate process mining','18. Use process mining in Power Automate','19. Manage process mining projects','20. Create Power BI reports with Process Mining','21. Cloud Computing Fundamentals','22. Cybersecurity Fundamentals','23. Getting Started with Artificial Intelligence','24. Create and manage automated processes with Power Automate','25. Microsoft Certified: Power Platform Fundamentals (PL-900) - stretch','',
'APPLIED PROJECTS','1. Property Operations Data Baseline.','2. Executive Performance Dashboard.','3. Rental or Maintenance Workflow Automation.','4. PropTech Pilot Operating Model.','5. AI-Assisted Operations Proof of Concept using approved or synthetic data only.','',
'DEVELOPMENT KPIS','1. Integrated operating baseline by 31 August 2026.','2. Cloud and automation literacy by 31 October 2026.','3. First measurable prototype by 30 November 2026.','4. Transformation leadership evidence by 31 January 2027.','5. Four sanitised portfolio artefacts by 31 March 2027.','6. Scale-ready operating model by 30 June 2027.','',
'GOVERNANCE','Use least privilege, approved test environments and synthetic or authorised data.','Do not publish tenant, payment, identity, lease, legal-document or credential data.','Define ownership, lawful purpose, retention, access, audit, backup and rollback.','Measure benefits against an approved baseline and state assumptions and limitations.','',
'REVIEW AND SIGN-OFF','Participant: Alberto Antonio Carvalho Cabral Adao','Mentor and facilitator: Raydo Matthee','Formal reviews: 30, 60 and 90 days, then quarterly.','This generated PDF is a sanitised execution copy. The signed source IDR remains confidential.'
];
function esc(s){return s.normalize('NFKD').replace(/[^\x20-\x7E]/g,'-').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function pdf(){const pages=[];for(let i=0;i<lines.length;i+=46)pages.push(lines.slice(i,i+46));const o=[];const ids=pages.map((_,i)=>4+i*2);o[1]='<< /Type /Catalog /Pages 2 0 R >>';o[2]=`<< /Type /Pages /Kids [${ids.map(id=>`${id} 0 R`).join(' ')}] /Count ${pages.length} >>`;o[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';pages.forEach((page,i)=>{const pid=4+i*2,cid=pid+1,cmd=['BT','/F1 9 Tf','42 748 Td','13 TL'];page.forEach((line,n)=>{if(n===0)cmd.push(`/F1 14 Tf (${esc(line)}) Tj`,'/F1 9 Tf','T*');else cmd.push(`(${esc(line)}) Tj`,'T*')});cmd.push('ET');const stream=cmd.join('\n');o[pid]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${cid} 0 R >>`;o[cid]=`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`});let out='%PDF-1.4\n';const offsets=[0];for(let i=1;i<o.length;i++){offsets[i]=out.length;out+=`${i} 0 obj\n${o[i]}\nendobj\n`}const xref=out.length;out+=`xref\n0 ${o.length}\n0000000000 65535 f \n`;for(let i=1;i<o.length;i++)out+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;return out+`trailer\n<< /Size ${o.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`}
export default function DownloadIdrButton({className='button button--primary button--lg',label='Download PDF IDR'}){function download(){const url=URL.createObjectURL(new Blob([pdf()],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download='Alberto_Adao_Individual_Development_Roadmap.pdf';a.click();URL.revokeObjectURL(url)}return <button className={className} type="button" onClick={download}>{label}</button>}
